### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by Anthony6444** [xavier2910/thetundra#3]
Linux releases would be nice

**Comment by xavier2910** [comment]
Yes. That's your job.
Get [stack](docs.haskellstack.org), download source, navigate to source dir, `stack install`, and upload the bin (it should be at `usr/bin`, I think. see the docs)

**Comment by xavier2910** [comment]
Since you are currently my entire linux user base, whereas everyone else runs windows, I assumed you were capable of building it yourself.

**Comment by xavier2910** [comment]
Ok, so I also have linux now, so linux binaries should be forthcoming
